version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python libssl-dev openssl repo rsync flex bison
           git config --global user.name "phoenix-1708"
           git config --global user.email "harikumar1708@gmail.com"
           git config --global color.ui true
           git clone https://github.com/phoenix-1708/scripts && cd scripts && bash setup/android_build_env.sh && cd ..
           mkdir phoenix
           cd phoenix
           wget https://raw.githubusercontent.com/phoenix-1708/android_kernel_xiaomi_sweet/arrow-11.0/.circleci/build1.sh
           source build1.sh
           wget https://raw.githubusercontent.com/phoenix-1708/android_kernel_xiaomi_sweet/arrow-11.0/.circleci/zip.sh
           source zip.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
