# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the arrow-11.0 branch
  push:
    branches: [ arrow-11.0 ]
  pull_request:
    branches: [ arrow-11.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Going to start
        run: echo started

      # Runs a set of commands using the runners shell
      - name: compile
        run: |
          sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev openssl repo rsync flex bison gcc-aarch64-linux-gnu
          git config --global user.name "phoenix-1708"
          git config --global user.email "harikumar1708@gmail.com"
          git config --global color.ui true
          git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..
          wget https://raw.githubusercontent.com/phoenix-1708/android_kernel_xiaomi_sweet/arrow-11.0/.circleci/build.sh
          source build.sh
 
